[versions]
agp = "8.9.1"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
supportV4 = "28.0.0"

[libraries]
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
support-v4 = { module = "com.android.support:support-v4", version.ref = "supportV4" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

